package utility.enums;

public enum ErrorType {

	INVALID_CREDENTIALS_WRONG_PASSWORD("INVALID_CREDENTIALS_WRONG_PASSWORD"),
	INVALID_CREDENTIALS_USER_NOT_FOUND("INVALID_CREDENTIALS_USER_NOT_FOUND"),
	INVALID_CREDENTIALS_USER_ALREADY_LOGGED_IN("INVALID_CREDENTIALS_USER_ALREADY_LOGGED_IN"),
	INVALID_W4_VALUE_NOT_FOUND("INVALID_W4_VALUE_NOT_FOUND"),
	INVALID_CREDENTIALS_RESTAURANT_NOT_FOUND("INVALID_CREDENTIALS_RESTAURANT_NOT_FOUND"),
	CLIENT_ALREADY_EXIST("CLIENT_ALREADY_EXIST"),
	BUSINESS_DOESNT_EXIST("BUSINESS_DOESNT_EXIST"),
	BUSINESS_NOT_APPROVE("BUSINESS_NOT_APPROVE"),
	WORKER_DOSENT_EXIST("WORKER_DOSENT_EXIST"),
	WORKER_DOSENT_RESTAURANT_OWNER("WORKER_DOSENT_RESTAURANT_OWNER"),
	DISHES_NOT_FOUND("DISHES_NOT_FOUND"),
	UNKNOWN("UNKNOWN_ERROR_TYPE");																//used internally, should not be sent as a type
	
	private String errorType;
	
	private ErrorType(String errorType) {
		this.errorType = errorType;
	}
	
	@Override
	public String toString() {
		return errorType;
	}
	
	public static ErrorType fromString(String errorTypeString) {
		switch(errorTypeString) {
		case "INVALID_CREDENTIALS_WRONG_PASSWORD":
			return ErrorType.INVALID_CREDENTIALS_WRONG_PASSWORD;
		case "INVALID_CREDENTIALS_USER_NOT_FOUND":
			return ErrorType.INVALID_CREDENTIALS_USER_NOT_FOUND;
		case "INVALID_CREDENTIALS_USER_ALREADY_LOGGED_IN":
			return ErrorType.INVALID_CREDENTIALS_USER_ALREADY_LOGGED_IN;
		case "INVALID_W4_VALUE_NOT_FOUND":
			return ErrorType.INVALID_W4_VALUE_NOT_FOUND;
		case "CLIENT_ALREADY_EXIST":
			return ErrorType.CLIENT_ALREADY_EXIST;
		case "BUSINESS_NOT_APPROVE":
			return BUSINESS_NOT_APPROVE;
		case "BUSINESS_DOESNT_EXIST":
			return BUSINESS_DOESNT_EXIST;
		case "WORKER_DOSENT_EXIST":
			return WORKER_DOSENT_EXIST;
		case "WORKER_DOSENT_RESTAURANT_OWNER":
			return WORKER_DOSENT_RESTAURANT_OWNER;
		case "INVALID_CREDENTIALS_RESTAURANT_NOT_FOUND":
			return ErrorType.INVALID_CREDENTIALS_RESTAURANT_NOT_FOUND;
		case "DISHES_NOT_FOUND":
			return ErrorType.DISHES_NOT_FOUND;
		default:
			return ErrorType.UNKNOWN;
		}
	}
}
