package utility.enums;

public enum ErrorType {

	INVALID_CREDENTIALS_WRONG_PASSWORD("INVALID_CREDENTIALS_WRONG_PASSWORD"),
	INVALID_CREDENTIALS_USER_NOT_FOUND("INVALID_CREDENTIALS_USER_NOT_FOUND"),
	INVALID_CREDENTIALS_USER_ALREADY_LOGGED_IN("INVALID_CREDENTIALS_USER_ALREADY_LOGGED_IN"),
	INVALID_W4_VALUE_NOT_FOUND("INVALID_W4_VALUE_NOT_FOUND"),
	INVALID_CREDENTIALS_RESTAURANT_NOT_FOUND("INVALID_CREDENTIALS_RESTAURANT_NOT_FOUND"),
	CLIENT_ALREADY_EXIST("CLIENT_ALREADY_EXIST"),
	DISHES_NOT_FOUND("DISHES_NOT_FOUND"),
	UNKNOWN("UNKNOWN_ERROR_TYPE"),  			//used internally, should not be sent as a type
	ORDERS_NOT_FOUND("ORDERS_NOT_FOUND");			
	
	private String errorType;
	
	private ErrorType(String errorType) {
		this.errorType = errorType;
	}
	
	@Override
	public String toString() {
		return errorType;
	}
	
	public static ErrorType fromString(String errorTypeString) {
		switch(errorTypeString) {
		case "INVALID_CREDENTIALS_WRONG_PASSWORD":
			return ErrorType.INVALID_CREDENTIALS_WRONG_PASSWORD;
		case "INVALID_CREDENTIALS_USER_NOT_FOUND":
			return ErrorType.INVALID_CREDENTIALS_USER_NOT_FOUND;
		case "INVALID_CREDENTIALS_USER_ALREADY_LOGGED_IN":
			return ErrorType.INVALID_CREDENTIALS_USER_ALREADY_LOGGED_IN;
		case "INVALID_W4_VALUE_NOT_FOUND":
			return ErrorType.INVALID_W4_VALUE_NOT_FOUND;
		case "CLIENT_ALREADY_EXIST":
			return ErrorType.CLIENT_ALREADY_EXIST;
		case "INVALID_CREDENTIALS_RESTAURANT_NOT_FOUND":
			return ErrorType.INVALID_CREDENTIALS_RESTAURANT_NOT_FOUND;
		case "DISHES_NOT_FOUND":
			return ErrorType.DISHES_NOT_FOUND;
		default:
			return ErrorType.UNKNOWN;
		}
	}
}
